project:
  type: website

website:
  title: "rss-quarto"
  description: "demo of RSS feed"
  site-url: "https://www.fast.ai"
  navbar:
    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo
    css: styles.css



